### ISSUE TITLE
August 2015 import failed

### ISSUE THREAD

**Issue by victorantos** [gaganpreet/hn-hiring-mapped#6]
No jobs imported for this month.

**Comment by victorantos** [comment]
Same issue for Sept'15

**Comment by gaganpreet** [comment]
Sorry it took me a while to get this fixed, been busy with things. Thanks for reporting!

**Comment by victorantos** [comment]
well done! thanks a lot you just fixed my website, I went to my [job board](http://angjobs.com/#!/jobs/inbox/hn) and saw immediately this month's job list! My auto-import worked flawlessly, thanks again! :)
